AllCops:
  DisabledByDefault: false
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
      - 'Rakefile'
      - 'Gemfile'
      - 'db/**/*'
      - 'config/**/*'
      - 'bin/**/*'

Documentation:
  Enabled: false
